name             'spree'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures spree'
long_description 'Installs/Configures spree'
version          '0.1.0'
